export const cars = [
    {id: 1, year:"2017",    make: "Toyota",     model: "Corolla",    color:"Silver",   price:"$15,497", image: "./assets/2017-toyota-corolla-silver.webp"},
    {id: 2, year:"2020",    make: "Toyota",     model: "Corolla",    color:"White",    price:"$24,990", image: "./assets/2020-toyota-corolla-white.webp"},
    {id: 3, year:"2019",    make: "Toyota",     model: "Camry",      color:"Red",      price:"$29,990", image: "./assets/2019-toyota-camry-red.jpg"},
    {id: 4, year:"2017",    make: "Toyota",     model: "Prius",      color:"Silver",   price:"$24,990", image: "./assets/2017-toyota-prius-silver.jpg"},
    {id: 5, year:"2015",    make: "Toyota",     model: "Highlander", color:"Black",    price:"$25,472", image: "./assets/2015-toyota-highlander-black.jpg"},
    {id: 6, year:"2022",    make: "Subaru",     model: "Forester",   color:"Blue",     price:"$35,999", image: "./assets/2022-subaru-forester-blue.jpg"},
    {id: 7, year:"2016",    make: "Subaru",     model: "Impreza",    color:"Silver",   price:"$19,995", image: "./assets/2015-subaru-impreza-silver.jpg"},
    {id: 8, year:"2017",    make: "Subaru",     model: "Crosstrek",  color:"White",    price:"$15,995", image: "./assets/2017-subaru-crosstrek-white.webp"},
    {id: 9, year:"2018",    make: "Nissan",     model: "Rogue",      color:"Blue",     price:"$20,990", image: "./assets/2018-nissan-rogue-blue.webp"},
    {id: 10, year:"2021",    make: "Nissan",     model: "Pathfinder", color:"Blue",     price:"$39,698", image: "./assets/2021-nissan-pathfinder-blue.webp"},
    {id: 11, year:"2018",    make: "GMC",        model: "Sierra",     color:"Black",    price:"$47,998", image: "./assets/2018-gmc-sierra-black.webp"},
    {id: 12, year:"2023",    make: "GMC",        model: "Hummer EV",  color:"White",    price:"$110,295", image: "./assets/2023-gmc-hummer-ev-white.webp"},
    {id: 13, year:"2019",    make: "Ford",       model: "Mustang",    color:"Yellow",   price:"$24,990", image: "./assets/2019-ford-mustang-yellow.webp"},
    {id: 14, year:"2013",    make: "Ford",       model: "F-150",      color:"Black",    price:"$18,898", image: "./assets/2013-ford-f150-black.jpg"},
    {id: 15, year:"2017",    make: "Volkswagon", model: "Jetta",      color:"Blue",     price:"$17,990", image: "./assets/2017-vw-jetta-blue.webp"},
    {id: 16, year:"2022",    make: "Volkswagon", model: "Atlas",      color:"Red",      price:"$44,600", image: "./assets/2022-vw-atlas-red.webp"},
    {id: 17, year:"2022",    make: "Tesla",      model: "Model S",    color:"Black",    price:"$92,800", image: "./assets/2022-tesla-model-s-black.webp"},
    {id: 18, year:"2021",    make: "Tesla",      model: "Model Y",    color:"White",    price:"$69,771", image: "./assets/2021-tesla-model-y-white.webp"},
    {id: 19, year:"2019",    make: "Dodge",      model: "Challenger", color:"Yellow",   price:"$32,590", image: "./assets/2019-dodge-challenger-yellow.webp"},
    {id: 20, year:"2014",    make: "Dodge",      model: "Charger",    color:"Silver",   price:"$16,777", image: "./assets/2014-dodge-charger-silver.webp"},
    {id: 21, year:"2011",    make: "Jeep",       model: "Wrangler",   color:"White",    price:"$19,995", image: "./assets/2011-jeep-wrangler-white.webp"},
    {id: 22, year:"2016",    make: "Jeep",       model: "Cherokee",   color:"White",    price:"$21,590", image: "./assets/2016-jeep-cherokee-white.webp"},
    {id: 23, year:"2018",    make: "Jeep",       model: "Compass",    color:"Brown",    price:"25,590", image: "./assets/2018-jeep-compass-brown.webp"},
    {id: 24, year:"2021",    make: "Maserati",   model: "Ghibli",     color:"Black",    price:"$115,085", image: "./assets/2021-maserati-ghibli-black.webp"}
                ];                            